/* Auto-generated by Puppet Craft. */
/* parentLayer: 0=root bone, 1=childBonesLayer1, 2=childBonesLayer2 */
#include <stddef.h>

typedef struct {
    const char *label;
    float x;
    float y;
    float angle;
    int spriteIndex;
    float baseSpriteRotation;
    int parentIndex;
    int parentLayer;
} PuppetCraftBone;

typedef struct {
    float x;
    float y;
    float angle;
    int timelineFrame;
    const char *label;
} PuppetCraftKeyframe;

typedef struct {
    float x;
    float y;
    float angle;
} PuppetCraftDeltaFrame;

typedef struct {
    const char *boneLabel;
    const PuppetCraftKeyframe *keyframes;
    int keyframeCount;
    const PuppetCraftDeltaFrame *bakedFrames;
    int bakedFrameCount;
    int timelineStart;
    int timelineEnd;
} PuppetCraftTrack;

typedef struct {
    const char *animationName;
    const PuppetCraftTrack *tracks;
    int trackCount;
} PuppetCraftAnimation;

typedef struct {
    const char *label;
    const char *spritesPath;
    float x;
    float y;
    float angle;
    const PuppetCraftBone *bones;
    int boneCount;
    const PuppetCraftAnimation *animations;
    int animationCount;
} PuppetCraftExport;

static const PuppetCraftBone mascot_bones[] = {
    {"mascotBone", 0.0f, -220.0f, 0.0f, 4, 1.57f, -1, 0},
    {"mascotSkullParent", 0.0f, 55.0f, 0.0f, -1, 0.0f, 0, 1},
    {"mascotSkull", 0.0f, -40.0f, 0.0f, 6, 1.57f, 1, 1},
    {"mascotSkullJawParent", 1.0f, 47.0f, 0.0f, -1, 0.0f, 2, 2},
    {"mascotSkullJaw", 0.0f, -18.0f, 0.0f, 7, 1.57f, 3, 1},
    {"mascotSkullEyesBack", 0.0f, 45.0f, 0.0f, 8, 0.0f, 2, 2},
    {"mascotSkullLeftEyeParent", 10.0f, 32.0f, 0.0f, -1, 0.0f, 2, 2},
    {"mascotSkullLeftEye", 0.0f, -14.0f, 0.0f, 9, 1.57f, 6, 1},
    {"mascotSkullRightEyeParent", -1.0f, 31.0f, 0.0f, -1, 0.0f, 2, 2},
    {"mascotSkullRightEye", 0.0f, -13.0f, 0.0f, 10, 1.57f, 8, 1},
    {"mascotReflectionParent", 13.0f, 49.0f, 0.0f, -1, 0.0f, 0, 1},
    {"mascotReflection", 0.0f, -25.0f, 0.0f, 5, 1.57f, 10, 1},
    {"mascotArmParent", 22.0f, 78.0f, 1.14f, -1, 0.0f, 0, 2},
    {"mascotArm2", 28.0f, 0.0f, 0.0f, 2, 0.0f, 12, 2},
    {"mascotArmElbow", 9.0f, 3.0f, 0.0f, -1, 0.0f, 13, 2},
    {"mascotArm1", 44.0f, 0.0f, 0.0f, 1, 0.0f, 14, 2},
    {"mascotWrist", 0.0f, 3.0f, 0.0f, -1, 0.0f, 15, 2},
    {"mascotHand", 34.0f, 0.0f, 0.0f, 3, 0.0f, 16, 1},
};

static const PuppetCraftKeyframe mascot_clip0_track0_keyframes[] = {
    {1.0f, 47.0f, 0.0f, 0, "frame1"},
    {-4.0f, 48.0f, 0.4f, 5, "frame2"},
    {1.0f, 47.0f, 0.0f, 10, "frame3"},
};

static const PuppetCraftDeltaFrame mascot_clip0_track0_baked_frames[] = {
    {-1.0f, 0.2f, 0.08f},
    {-1.0f, 0.2f, 0.08f},
    {-1.0f, 0.2f, 0.08f},
    {-1.0f, 0.2f, 0.08f},
    {-1.0f, 0.2f, 0.08f},
    {1.0f, -0.2f, -0.08f},
    {1.0f, -0.2f, -0.08f},
    {1.0f, -0.2f, -0.08f},
    {1.0f, -0.2f, -0.08f},
    {1.0f, -0.2f, -0.08f},
};

static const PuppetCraftTrack mascot_clip0_tracks[] = {
    {"mascotSkullJawParent", mascot_clip0_track0_keyframes, 3, mascot_clip0_track0_baked_frames, 10, 0, 10},
};

static const PuppetCraftKeyframe mascot_clip1_track0_keyframes[] = {
    {9.0f, 3.0f, 0.0f, 0, "frame1"},
    {9.0f, 3.0f, -2.1f, 10, "frame2"},
    {9.0f, 3.0f, 0.0f, 20, "frame3"},
};

static const PuppetCraftDeltaFrame mascot_clip1_track0_baked_frames[] = {
    {0.0f, 0.0f, -0.21f},
    {0.0f, 0.0f, -0.21f},
    {0.0f, 0.0f, -0.21f},
    {0.0f, 0.0f, -0.21f},
    {0.0f, 0.0f, -0.21f},
    {0.0f, 0.0f, -0.21f},
    {0.0f, 0.0f, -0.21f},
    {0.0f, 0.0f, -0.21f},
    {0.0f, 0.0f, -0.21f},
    {0.0f, 0.0f, -0.21f},
    {0.0f, 0.0f, 0.21f},
    {0.0f, 0.0f, 0.21f},
    {0.0f, 0.0f, 0.21f},
    {0.0f, 0.0f, 0.21f},
    {0.0f, 0.0f, 0.21f},
    {0.0f, 0.0f, 0.21f},
    {0.0f, 0.0f, 0.21f},
    {0.0f, 0.0f, 0.21f},
    {0.0f, 0.0f, 0.21f},
    {0.0f, 0.0f, 0.21f},
};

static const PuppetCraftKeyframe mascot_clip1_track1_keyframes[] = {
    {22.0f, 78.0f, 1.14f, 0, "frame1"},
    {22.0f, 78.0f, -0.06f, 10, "frame2"},
    {22.0f, 78.0f, 1.14f, 20, "frame3"},
};

static const PuppetCraftDeltaFrame mascot_clip1_track1_baked_frames[] = {
    {0.0f, 0.0f, -0.12f},
    {0.0f, 0.0f, -0.12f},
    {0.0f, 0.0f, -0.12f},
    {0.0f, 0.0f, -0.12f},
    {0.0f, 0.0f, -0.12f},
    {0.0f, 0.0f, -0.12f},
    {0.0f, 0.0f, -0.12f},
    {0.0f, 0.0f, -0.12f},
    {0.0f, 0.0f, -0.12f},
    {0.0f, 0.0f, -0.12f},
    {0.0f, 0.0f, 0.12f},
    {0.0f, 0.0f, 0.12f},
    {0.0f, 0.0f, 0.12f},
    {0.0f, 0.0f, 0.12f},
    {0.0f, 0.0f, 0.12f},
    {0.0f, 0.0f, 0.12f},
    {0.0f, 0.0f, 0.12f},
    {0.0f, 0.0f, 0.12f},
    {0.0f, 0.0f, 0.12f},
    {0.0f, 0.0f, 0.12f},
};

static const PuppetCraftTrack mascot_clip1_tracks[] = {
    {"mascotArmElbow", mascot_clip1_track0_keyframes, 3, mascot_clip1_track0_baked_frames, 20, 0, 20},
    {"mascotArmParent", mascot_clip1_track1_keyframes, 3, mascot_clip1_track1_baked_frames, 20, 0, 20},
};

static const PuppetCraftKeyframe mascot_clip2_track0_keyframes[] = {
    {144.0f, 189.0f, -2.0f, 0, "frame1"},
    {144.0f, 189.0f, -1.0f, 10, "frame2"},
    {144.0f, 189.0f, -2.0f, 20, "frame3"},
};

static const PuppetCraftDeltaFrame mascot_clip2_track0_baked_frames[] = {
    {0.0f, 0.0f, 0.1f},
    {0.0f, 0.0f, 0.1f},
    {0.0f, 0.0f, 0.1f},
    {0.0f, 0.0f, 0.1f},
    {0.0f, 0.0f, 0.1f},
    {0.0f, 0.0f, 0.1f},
    {0.0f, 0.0f, 0.1f},
    {0.0f, 0.0f, 0.1f},
    {0.0f, 0.0f, 0.1f},
    {0.0f, 0.0f, 0.1f},
    {0.0f, 0.0f, -0.1f},
    {0.0f, 0.0f, -0.1f},
    {0.0f, 0.0f, -0.1f},
    {0.0f, 0.0f, -0.1f},
    {0.0f, 0.0f, -0.1f},
    {0.0f, 0.0f, -0.1f},
    {0.0f, 0.0f, -0.1f},
    {0.0f, 0.0f, -0.1f},
    {0.0f, 0.0f, -0.1f},
    {0.0f, 0.0f, -0.1f},
};

static const PuppetCraftTrack mascot_clip2_tracks[] = {
    {"", mascot_clip2_track0_keyframes, 3, mascot_clip2_track0_baked_frames, 20, 0, 20},
};

static const PuppetCraftAnimation mascot_animations[] = {
    {"jawAnimation", mascot_clip0_tracks, 1},
    {"raisingArmParent", mascot_clip1_tracks, 2},
    {"waving", mascot_clip2_tracks, 1},
};

const PuppetCraftExport mascot_export = {
    "mascotRoot",
    "sprites_mascot",
    120.0f,
    250.0f,
    0.0f,
    mascot_bones,
    18,
    mascot_animations,
    3,
};
